--- 
javascripts: 
- base: 
  - prototype
  - jquery-1.3.2.min
  - jquery_prototype_compatibility
  - effects
  - controls
  - application
  - calendar
stylesheets:
- base: 
  - page
  - defaults
  - card
  - settings
